#include <cstdlib>
#include <cstring>
#include <cstdio>
#include <iostream>
#include <sstream>
#include <iomanip>
#include <cmath>
#include <bits/stdc++.h>
#include <cerrno>
#include <ctime>

double cube(double);
double cubeRoot(double);

unsigned int countBits(unsigned int);

int main()
{
	std::cout << "--------------------------------------------------------" << std::endl;
	std::cout << "-                  Assignment 12 - Misc                -" << std::endl;
	std::cout << "--------------------------------------------------------" << std::endl;
	std::cout << "-              George Good - CS1C 2:30 M/W             -" << std::endl;
	std::cout << "--------------------------------------------------------" << std::endl;
	std::cout << "This program is split into 4 parts." << std::endl;
	//cout << "This program will be using the STL <queue> class for its queue." << endl;
	std::cout << "Part 1: Using the built-in time functions, the program will" << std::endl;
	std::cout << "print today's date, then the date 88 days from today. Finally," << std::endl;
	std::cout << "it will print out the number of days between July 25 and December 24." << std::endl;
	std::cout << "Part 2: Using the built-in math routines, the program will print error" << std::endl;
	std::cout << " messages generated by attempting impossible calculations. " << std::endl;
	std::cout << "Part 3: Using pointers to functions, the program will call 2 math functions."	<< std::endl;
	std::cout << "Part 4: Using bitwise operators, the program will convert ASCII chars to" << std::endl;
	std::cout << "ints and then count how many active bits they contain. " << std::endl;
	std::cout << std::endl << "Program Start!" << std::endl;
//* 
    std::cout << "Part 1: Testing Time Functions... " << std::endl;
	

	
	std::cout << "Part 3: Pointers to Functions " << std::endl;
	std::cout << "Creating function pointer...";
	
	double (*fpoint)(double);

	std::cout << "Done! Calling Cube function via pointer..." << std::endl;
	
	fpoint = &cube;
	std::cout << "Input 4.4, result: " << fpoint(4.4) << std::endl;
	
	std::cout << "Done! Calling Cube Root function via pointer..." << std::endl;
	
	fpoint = &cubeRoot;
	std::cout << "Input 4.4, result: " << fpoint(4.4) << std::endl << std::endl;
	
	std::cout << "Part 4: Creating char array... ";
		char array[62] = { 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r',
		's','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N',
			'O','P','Q','R','S','T','U','V','W','X','Y','Z','1','2','3','4','5','6','7','8','9','0' };
	std::cout << " Initiating loop... " << std::endl;
	char buffer; 
	
	for (int i = 0; i<62; i++)
	{
		buffer = array[i];
		
		unsigned int intCheck = (unsigned int)buffer;
		
		std::cout << "Char " << array[i] << "'s ASCII value: " << intCheck << ", Number of Active Bits: " << countBits(intCheck) << std::endl;
	}
	
	std::cout << std::endl << "Finished!" << std::endl << "Program End" << std::endl;

	return 0;
}

double cube(double input)
{
	double result;
	
	result = input * input * input;
	
	return result;
}

double cubeRoot(double input)
{
	double result;
	
	result = std::cbrt(input);
	
	return result;
}

unsigned int countBits(unsigned int check) 
{ 
    unsigned int count = 0; 
    while (check) { 
        count += check & 1; 
        check >>= 1; 
    } 
    return count; 
} 
