#include <cstdlib>
#include <cstring>
#include <cstdio>
#include <iostream>
#include <sstream>
#include <iomanip>

#include "linkedListType.h"
#include "linkedListIterator.h"
#include "unorderedLL.h"

int main()
{
	std::cout << "--------------------------------------------------------" << std::endl;
	std::cout << "-              Assignment 13 - Linked List             -" << std::endl;
	std::cout << "--------------------------------------------------------" << std::endl;
	std::cout << "-              George Good - CS1C 2:30 M/W             -" << std::endl;
	std::cout << "--------------------------------------------------------" << std::endl;
	std::cout << "This program is split into 4 parts." << std::endl;
	std::cout << "Part 1: Using the built-in time functions, the program will" << std::endl;
	std::cout << "print today's date, then the date 88 days from today. Finally," << std::endl;
	std::cout << "it will print out the number of days between July 25 and December 24." << std::endl;
	std::cout << "Part 2: Using the built-in math routines, the program will print error" << std::endl;
	std::cout << " messages generated by attempting impossible calculations. " << std::endl;
	std::cout << "Part 3: Using pointers to functions, the program will call 2 math functions."	<< std::endl;
	std::cout << "Part 4: Using bitwise operators, the program will convert ASCII chars to" << std::endl;
	std::cout << "ints and then count how many active bits they contain. " << std::endl;
	std::cout << std::endl << "Program Start!" << std::endl;
	
	
	
	std::cout << std::endl << "Program End" << std::endl;
	return 0;
}